# Generated by Django 5.0.10 on 2024-12-16 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='send_on',
            new_name='sent_on',
        ),
    ]
